### ISSUE TITLE
LSPosed does not open 

### ISSUE THREAD

**Issue by FreePhoenix888** [mywalkb/LSPosed_mod#146]
### Steps to reproduce

1. Install my ROM on my device
2. Flash lsposed
3. Reboot
4. Try to open from notification and see nothing

### Expected behaviour

LSPosed to open

### Actual behaviour

Context:
- Device: Redmi Note 8 (ginkgo)
- ROM: crDroid 10.7
- Android: 14
- Magisk: 27.0
- Is Magisk rebuilt with random name: Yes
- Zygisk: Enabled, for the most of the apps
Problem Description:
LSPosed does not open
I have tried 3 variants of LSposed:
https://github.com/LSPosed/LSPosed
https://github.com/mywalkb/LSPosed_mod
https://github.com/JingMatrix/LSPosed
I install zygisk variant. By using magisk modules. After reboot module is successfully installed and I have a notification. But when I tap it - nothing happens
Note: some man recommended me to disable zygisk and use https://github.com/Dr-TSNG/ZygiskNext instead (which I do not like because I have not found how to enable Deny List when using this zygisk). In this case I see error when I tap notification:
```
time: 1726835972333
msg: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
stacktrace: java.lang.RuntimeException: Unable to instantiate application org.lsposed.manager.App package com.android.shell: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1474)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7361)
at java.lang.reflect.Method.invoke(Native Method)
at AyfemFk.n.zi.DCZLj.f.Epn.XCLh.HookBridge.invokeOriginalMethod(Native Method)
at J.callback(Unknown Source:193)
at LSPHooker_.handleBindApplication(Unknown Source:11)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8594)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at android.app.Instrumentation.newApplication(Instrumentation.java:1354)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
... 15 more
```

### Xposed Module List

```shell
Nothing
```

### Magisk Module List

```shell
Nothing
```

### LSPosed version

1.9.3

### Android version

14

### Magisk version

27

### Riru version

N/A

### Version requirement

- [X] I am using latest debug CI version of LSPosed and enable verbose log

### Logs

```
time: 1726835972333
msg: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
stacktrace: java.lang.RuntimeException: Unable to instantiate application org.lsposed.manager.App package com.android.shell: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1474)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7361)
at java.lang.reflect.Method.invoke(Native Method)
at AyfemFk.n.zi.DCZLj.f.Epn.XCLh.HookBridge.invokeOriginalMethod(Native Method)
at J.callback(Unknown Source:193)
at LSPHooker_.handleBindApplication(Unknown Source:11)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8594)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lsposed.manager.App" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Shell/lib/arm64, /system/lib64, /system/system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at android.app.Instrumentation.newApplication(Instrumentation.java:1354)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
... 15 more
```

**Comment by flakysilverfish** [comment]
I am facing the same problem.

**Comment by FreePhoenix888** [comment]
> I am facing the same problem.

Check this: https://github.com/JingMatrix/LSPosed/issues/38
