### ISSUE TITLE
I can't enable "AppErrorTracking" module[Bug] 

### ISSUE THREAD

**Issue by RashadGasimly** [mywalkb/LSPosed_mod#20]
### Steps to reproduce/复现步骤

1.I downloaded and installed apperrortracking module from repositories
2.I can't enable this module

### Expected behaviour/预期行为

I can't enable this module (can't open)

### Actual behaviour/实际行为

This module cannot enable

### Xposed Module List/Xposed 模块列表

```shell
AOSP Mods
NoStorageRestrict
XCallRecordingSettings
Installer++
AppErrorTracking
```

### Magisk Module List/Magisk 模块列表

```shell
AOSP Mods (Xposed)
Gpu Driver
Magical Overlayfs
microG installer revived
YouTube Revanced Extended
Shamiko
ZygiskOnKernelSU
LSPosed (Zygisk)
```

### LSPosed version/LSPosed 版本

1.9.1_mod (7145) (debug)

### Android version/Android 版本

Android 13 (Tiramisu)

### Magisk version/Magisk 版本

KernelSU version: 0.6.7-25 -xxxxxxxxx (11235)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-14T20_56_25.204066.zip](https://github.com/mywalkb/LSPosed_mod/files/12611455/LSPosed_2023-09-14T20_56_25.204066.zip)

**Comment by mywalkb** [comment]
Can you open the app without enable the module in LSPosed's app?

**Comment by mywalkb** [comment]
I tried to replicate your issue without success. I tested on real android 12 and works, I tested on avd android 13 and works.
I can activate the module and after reboot is activated, the app detect is activated.
I will try with kernelsu.

![screen](https://github.com/mywalkb/LSPosed_mod/assets/66966897/a65e2f96-bc09-4b57-9aa8-6a9d907244a8)

**Comment by mywalkb** [comment]
Many apps in your device are skipped, kernelsu is not fully supported in this moment.
Try to install original LSPosed and make an issue in original repository if the developers will fix, automatically will be fixed in this mod.

In your logs I saw this:
```
[ 2023-09-14T16:00:06.452        0:   793:  2124 E/LSPosedService  ] get denylist
android.database.sqlite.SQLiteException: no such table: settings (code 1 SQLITE_ERROR): , while compiling: SELECT value FROM settings WHERE `key`=?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1712)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1559)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1430)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1598)
        at org.lsposed.lspd.service.ConfigManager.getDenyListPackages(ConfigManager.java:1194)
        at org.lsposed.lspd.service.ConfigManager.cacheScopes(ConfigManager.java:664)
        at org.lsposed.lspd.service.ConfigManager.updateAppCache(ConfigManager.java:993)
        at org.lsposed.lspd.service.LSPosedService.dispatchPackageChanged(LSPosedService.java:181)
        at org.lsposed.lspd.service.LSPosedService.$r8$lambda$qyw7DCt-dubgYNaq6lkZzIgJOXw(Unknown Source:0)
        at org.lsposed.lspd.service.LSPosedService$$ExternalSyntheticLambda10.accept(Unknown Source:4)
        at org.lsposed.lspd.service.LSPosedService$1.lambda$performReceive$0(LSPosedService.java:349)
        at org.lsposed.lspd.service.LSPosedService$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

with build 7145 shouldn't happen for this bbcb9cad5cfe8a52c3dbd54190491e00d8f2c8bb . When magisk db doesn't exist as in kernelsu, no query should be executed

**Comment by rushizgithub** [comment]
> Owne

can you share guide to root avd and install lsposed?
